# GET the home route
GET http://localhost:3000/

###

# GET all locations
GET http://localhost:3000/api/locations

###

# GET a specific location by ID
GET http://localhost:3000/api/locations/1

###

# DELETE a location by ID
DELETE http://localhost:3000/api/locations/12

###

# POST a new location
POST http://localhost:3000/api/locations/
Content-Type: application/json

{
  "latitude": 90,
  "longitude": 60
}

###

# PUT to update a location by ID
# Replace ID and values as needed
PUT http://localhost:3000/api/locations/1
Content-Type: application/json

{
  "latitude": 70,
  "longitude": 70
}

###

# PATCH to partially update a location by ID
# Replace ID and values as needed
PATCH http://localhost:3000/api/locations/15
Content-Type: application/json

{
  "latitude": 65
}

###

# GET all locations with FILTER (e.g., filter by latitude)
# Replace query parameters as needed
GET http://localhost:3000/api/locations?longitude=60

###

# GET all locations with SORT (e.g., sort by latitude)
# Replace query parameters as needed
GET http://localhost:3000/api/locations?sort=latitde&oder=dsc&longitude=60